version: '3.8'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      CONN_STR: mongodb://root:root@127.0.0.1
    ports:
      - '27017:27017'
    networks:
      - node-network

networks:
  node-network:
    driver: bridge